#+TITLE: Reframe Games

Games built in ClojureScript, with [[https://github.com/reagent-project/reagent][Reagent]], [[https://github.com/day8/re-frame][Re-frame]], [[https://github.com/thheller/shadow-cljs][Shadow-cljs]], and
[[https://github.com/nostalgic-css/NES.css][NES.css]].

This repo will be expanded to include other games, but for now, it's just a
Tetris clone. Check out the live game at [[https://russmatney.itch.io/tetruss][russmatney.itch.io/tetruss]].

* Tetruss
The [[https://tetris.wiki][Tetris Wiki]] has some great Tetris related resources.

**** Ideas, Version 2, and Punted Features/Issues
- [ ] mobile touch/gesture support
- [ ] customizable controls
- [ ] rotation styles on rows
- [ ] bullet mode: size-3 pieces, 10x speed
- [ ] draw your own piece
- [ ] build up a puzzle/art piece
- [ ] record and show replay/highlights
- [ ] shared high-score + leaderboard
- [ ] configurable pieces and board size
- [ ] bonus for clearing the screen completely
- [ ] controls: instant-drop
- [ ] high-score, custom controls preserved across re-fresh
- [ ] rows-to-next-level visual indication
- [ ] refactor colors into view, rather than attached to cells
- [ ] 'doom' face - show emotion during left/right/rotate/score
- [ ] Add achievements
- [ ] poster-ized level clears (gunn style)
  include current game state metadata
- [ ] display character commentary per piece played
- [ ] rotate in two directions
- [ ] show 'ghost' piece (for fast drop)
- [ ] mobile detection and 'alert'?
- [ ] pause doesn't always stop the clock?
**** Build and Deploy
***** Building the release
#+BEGIN_SRC sh
# remove 'complied' dir from dev-mode
rm -rf public/js/compiled

# build release version
shadow-cljs release app
#+END_SRC
***** Deploying to s3
#+BEGIN_SRC sh
# deploy to s3
aws s3 sync public/ s3://games.russmatney.com
#+END_SRC

******* Requires aws cli tool:
#+BEGIN_SRC zsh
yay -S aws-cli

# setup creds
aws configure
#+END_SRC

***** Packaging for itch.io
Itch.io requires a .zip of the web-app.

Build as described above, then zip it up.

#+BEGIN_SRC sh
zip -r reframe-games.zip public
#+END_SRC
* Mean-bean Machine clone
**** V1
***** [X] engine basics
***** [ ] break build process apart to support multiple apps
***** [ ] controls: hold
***** [ ] controls: no movement after initial contact
***** [ ] score calculated
***** [ ] presentation: hold
***** [ ] presentation: queue
***** [ ] presentation: score
***** [ ] presentation: controls
* Contributing
My intention for this repository is to build some things from scratch on my
own - selfishly, I'm somewhat closed-minded to contributions.

I'm open to talking about the things in here via PRs and Issues, and I encourage
you to fork and do what you want with the code!

My motivation for developing this in the public:
- to share the code as an example
- to get feedback
- (hopefully) to inspire others to build things!
